# Site settings
title: Traveler's life journey 
description: Traveler's life journey
favicon: /assets/img/avatar.JPG
baseurl: https://cofire2.github.io/
url: https://cofire2.github.io/
rss_url: /pages/atom.xml
google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Traveler
  title: A lonely traveler
  address: china
  email: Traveler@163.com
  link: http://cofire.github.io
  weibo:
  github: cofire
  linkedin: cofire
  twitter: cofire
  gavatar: /assets/img/avatar.JPG
  stackoverflow:
#  stackoverflow: 4582127
  workHistory:
    - work6:
      company: 外出求学路
      location: 宜春市, 江西省，中国---->上海，中国
      started: 2013
      duration: 2013
      description: 在那一年的八月，哥哥送我踏上了外出求学路。
    - work5:
      company: 寒窗多年,一朝折桂
      location: 宜春市, 江西省，中国
      started: 2013
      duration: 2013
      description: 辛苦12年到了收获的季节，在13年的数据，传来喜讯，高中了。
    - work4:
      company: 荣升高中
      location: 宜春市, 江西省，中国
      started: 2010
      duration: 2010
      description: 县里只有两所高中，一所好的，另一所职高，努努力，咬咬牙进入了高中。
    - work3:
      company: 升学
      location: 宜春市, 江西省，中国
      started: 2007
      duration: 2007
      description: 九年义务教育一眨眼就完成了一多半，在07年的夏秋交际，进入了镇里的中学。
    - work2:
      company: 转校
      location: 宜春市, 江西省，中国
      started: 2005
      duration: 2005
      description: 村里的小学只有一到四年级，读完了也就该外出求学了，这一年我就走入了新校门，到了乡里的小学。离开了家，走上了住宿的道路。
    - work1:
      company: 迈进校门
      location: 宜春市, 江西省，中国
      started: 2001
      duration: 2001
      description: 到了读书的年纪，既没有上幼儿园，也没上学前班，腿一伸就成了小学生。
    - work0:
      company: 平淡无奇的出生
      location: 宜春市, 江西省，中国
      started: 1995
      duration: 1995
      description: 不像其他的伟人，出生时或天降祥瑞，或七彩祥云，至少也是狂风暴雨的，而我就没听说我出生时有什么异象。
  educationHistory:
    - education1:
      organization: 平淡无奇的出生
      location: 宜春市, 江西省，中国
      degree: Bachelor
      major: Software Engineering
      started: 1995
      duration: 1995-2001
      description: 不像其他的伟人，出生时或天降祥瑞，或七彩祥云，至少也是狂风暴雨的，而我就没听说我出生时有什么异象。
  languages:
    - language1:
      name: Chinese
      proficiency: Native
    - language2:
      name: English
      proficiency: Professional
    - language3:
      name: Japanese
      proficiency: Limit
  programmingSkills:
    - skill1:
      name: HTML
      percentage: 100%
    - skill2:
      name: Bootstrap
      percentage: 90%
    - skill3:
      name: JavaScript
      percentage: 70%
    - skill4:
      name: AngularJS
      percentage: 70%
    - skill5:
      name: Java/Java EE
      percentage: 90%
